blog/urls.py
from django.conf.urls import url

from blog import views

urlpatterns = [
    url(r'^$', views.index, name='blog_index'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<title>[^/]+)/$',
        views.post_page, name='post_page'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$',
        views.index_day, name='index_day'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$',
        views.index_month, name='index_month'),
    url(r'^(?P<year>\d{4})/$', views.index_year, name='index_year'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'website.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^', include('personal_pages.urls', namespace="personal_pages")),
]

personal_pages/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

urlpatterns = [
        url(r'^$', TemplateView.as_view(template_name='personal_pages/index.html')),
        ]

personal_pages/views.py
from django.shortcuts import render

from django.http import HttpResponse

def main(request):
    return HttpResponse("Hello World.  Personal pages here")

personal_pages/templates/personal_pages/index.html
<!DOCTYPE html>
<!-- Load Django static files  -->
{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<link rel="shortcut icon" type="image/x-icon"  href="{% static 'blog/favicon.ico' %}"/>

	<title> Welcome to my web... site! </title>

    <!-- Bootstrap core CSS -->
	<link type="text/css"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
	<link type="text/css" href="{% static 'blog/bloggy.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item" href="#">Blog</a>
          <a class="blog-nav-item active" href="#">Home</a>
          <a class="blog-nav-item" href="#">Resume</a>
          <a class="blog-nav-item" href="#">Projects</a>
          <a class="blog-nav-item" href="#">About Me</a>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">The TeaSea Blog</h1>
        <p class="lead blog-description">A haphazard collection of miscellany</p>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">
          </nav>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Mathematics and Physics nerd here, finding new things out every day! </p>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
			  {% for date in blogged_months %}
			  <li><a href="{% url 'blog:index_month' year=date.0 month=date.1 %}">{{ date.2 }} {{ date.0 }} </a></li>
			  {% endfor %}
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="https://github.com/CT-TeaSea">GitHub</a></li>
              <li><a href="http://stackexchange.com/users/5642231/ct-teasea">Stack Exchange</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
	<script src="{% static 'blog/blog.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
	<!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
  </body>
</html>